CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'user',
    name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    ssn VARCHAR2(11) UNIQUE
);

CREATE TABLE customers (
    user_id NUMBER PRIMARY KEY,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    name VARCHAR2(50),
    last_name VARCHAR2(50),
    balance NUMBER DEFAULT 0
);

-- Insert these users into the customers table
INSERT INTO customers (user_id, name, last_name, balance)
SELECT user_id, name, last_name, 0
FROM users
WHERE username IN ();

CREATE TABLE admins (
    user_id NUMBER PRIMARY KEY,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    name VARCHAR2(50),
    last_name VARCHAR2(50)
);

CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    amount NUMBER,
    transaction_type VARCHAR2(20),
    transaction_date DATE DEFAULT SYSDATE
);