-- Basic database schema for our banking application.


-- USERS table stores core login information for each user
-- A user is any person who can log into the system and is apart of the system, including customers and admins
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(50),        
    last_name VARCHAR2(50),   
    username VARCHAR2(50) UNIQUE, 
    email VARCHAR2(100),      
    password VARCHAR2(100),   
    ssn VARCHAR2(11)          
);

-- CUSTOMERS table stores banking-specific info and links to USERS
CREATE TABLE customers (
    user_id NUMBER PRIMARY KEY, -- Links directly to USERS table
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    name VARCHAR2(50),          
    last_name VARCHAR2(50),     
    balance NUMBER DEFAULT 0    -- Account balance
);

-- TRANSACTIONS table logs all user financial transactions
CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unique transaction ID
    user_id NUMBER,                       -- Linked to user performing the transaction
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    amount NUMBER,                        -- Positive or negative transaction amount
    transaction_type VARCHAR2(20),        -- Deposit, withdrawal, etc.
    transaction_date DATE DEFAULT SYSDATE -- Date of transaction
);

-- LOGS table tracks failed logins, suspicious activity, etc.
CREATE TABLE logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unique log entry
    user_id NUMBER,                          -- Affected user
    log_type VARCHAR2(30),                   -- Type of log: 'failed_login', 'sql_injection_attempt', etc.
    timestamp DATE DEFAULT SYSDATE,          -- Time of the event
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);