CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(100),
    role VARCHAR2(20) DEFAULT 'user'
);



INSERT INTO users (username, password, role) VALUES ('allanSal1', 'password', 'admin');
INSERT INTO users (username, password, role) VALUES ('anib4l', 'csci32', 'admin');
INSERT INTO users (username, password, role) VALUES ('stev98n', 'pc123', 'admin');
INSERT INTO users (username, password) VALUES ('c98_Gomez', 'abc122');

COMMIT;